jdk: JDK_TAR_GZ_FILE_NAME
jdk_path: JDK_TAR_GZ_FILE_NAME_INC_FILE_NAME
solr_xml: SOLR_XML_FILE_NAME
solr_xml_path: SOLR_XML_FILE_PATH_AND_NAME
core_name: SOLR_CORE_NAME
tarz_config_files: PATH_TO_SOLR_CIONFIG_TAR_GZ_FILE
tomcat_dest_folder: TOMCAT7_DEST_FOLER
solr_home_dest_foler: SOLR_BASE_FOLDER
Xmx: HEAP_SPACE_FOR_JVM (e.g. 1024m or 2gb etc)

