require 'securerandom'

extra_config = <<-EXTRA
# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_server_secret: #{SecureRandom.hex(96)}

# This was auto-generated by Rubber and is unique to your machine.  Feel free to regenerate if you'd like.
# You may want to move this to your rubber-secret.yml to keep it out of version control.
graylog_web_secret: #{SecureRandom.hex(96)}
EXTRA

append_to_file 'config/rubber/rubber-graylog.yml', "\n#{extra_config}"