<%
  @path = "/etc/filebeat/filebeat.yml"
%>

############################# Filebeat #####################################
filebeat:
  prospectors:
    -
      paths:
        - <%= shared_path %>/log/logstash_*.log*
      fields:
        environment: <%= Rubber.env %>
      fields_under_root: true
      ignore_older: 3h
      document_type: Logstasher
  registry_file: /var/lib/filebeat/registry
############################# Output ##########################################
output:
  logstash:
    hosts: ["127.0.0.1:9200"]    
