mongodb_data_dir: /mnt/mongodb
mongodb_log_dir: /var/log/mongodb
mongodb_log: "#{mongodb_log_dir}/mongodb.log"
mongodb_pid: "#{mongodb_data_dir}/mongod.lock"

roles:
  mongodb:
    packages: [mongodb-org mongodb-org-server mongodb-org-shell mongodb-org-mongos mongodb-org-tools]
